name: 自动构建
on: 
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build
        run: |
          npm install
          npm run build
          rm -rf ./node_modules
          zip -r ./lite_tools_v4.zip ./*
      - name: Upload Release File
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: lite_tools_v4.zip